// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ4TrBNfTjvRAGMtbobXX-W0mdlxqqeac',
    appId: '1:70267293643:web:9c38e13793e515bd15b04e',
    messagingSenderId: '70267293643',
    projectId: 'firstproject-e8fc3',
    authDomain: 'firstproject-e8fc3.firebaseapp.com',
    storageBucket: 'firstproject-e8fc3.appspot.com',
    measurementId: 'G-G74H2DY759',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeXay8Fcbo8I6koKv36jaq0BZS0ElEPvM',
    appId: '1:70267293643:android:87b0e72ad0dedd0415b04e',
    messagingSenderId: '70267293643',
    projectId: 'firstproject-e8fc3',
    storageBucket: 'firstproject-e8fc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7AwpLgVVsLzSI5PqHF16Ezmh6ustY9WA',
    appId: '1:70267293643:ios:cd4676bc012751aa15b04e',
    messagingSenderId: '70267293643',
    projectId: 'firstproject-e8fc3',
    storageBucket: 'firstproject-e8fc3.appspot.com',
    iosBundleId: 'com.example.userLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7AwpLgVVsLzSI5PqHF16Ezmh6ustY9WA',
    appId: '1:70267293643:ios:4dcde9a0afcd054b15b04e',
    messagingSenderId: '70267293643',
    projectId: 'firstproject-e8fc3',
    storageBucket: 'firstproject-e8fc3.appspot.com',
    iosBundleId: 'com.example.userLogin.RunnerTests',
  );
}
